spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/demodb
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console  # H2 콘솔에 접근할 URL 경로
  jpa:
    hibernate:
      ddl-auto: create # 프로그램 시작할 때마다 새로 생성
    show-sql: false # 실행할 때마다 쿼리문 출력 false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true # 하이버네이트 이후 data.sql 로드
  sql:
    init:
      mode: always # 프로그램 시작할 때 sql문 매번 실행
  data:
    rest:
      base-path: /api
      default-page-size: 3
      max-page-size: 5